# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
    paths: 
      - 'test/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
          ref: master
          path: master

    - name: Sysdig CIS Dockerfile Benchmark
      uses: sysdiglabs/benchmark-dockerfile@v1.0.0
      id: cis_dockerfile_benchmark
      with:
        disallowedPackages: 'netcat'
        secretPatterns: 'aws_secret,pass'
      
    # Purposely stop here
    - name: Post Run
      env:
        SYSDIG_MONITOR_TOKEN: ${{ secrets.SYSDIG_MONITOR_TOKEN }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_SHA: ${{ github.event.pull_request.head.sha }}
        PR_OWNER: ${{ github.event.pull_request.head.user.login }}
      run: |
        echo "###"
        echo "{\"pr_name\": \"${PR_TITLE}\", \"pr_sha\": \"${PR_SHA}\", \"pr_owner\": \"${PR_OWNER}\"}" > /tmp/report.json
        echo ${{ toJSON(steps.cis_dockerfile_benchmark.outputs.violation_report) }} > /tmp/report
        reportString=$(sed 's/"/\\"/g' /tmp/report)
        echo $reportString
        
        # send result to Sysdig monitor
        curl -X POST -s https://app.sysdigcloud.com/api/events -H 'Content-Type: application/json; charset=UTF-8' -H 'Authorization: Bearer '"${SYSDIG_MONITOR_TOKEN}"'' -d '{"event":{"name":"CIS Dockerfile Benchmark - PR: '"${PR_TITLE}"' ","description":"'"${reportString}"'","severity":"6"}}' --compressed
        echo "###"
        
        echo "Stop here!"
        exit 1
